### ISSUE TITLE
How to add fonts to this image?

### ISSUE THREAD

**Issue by atrudeau-vitall** [shelfio/libreoffice-lambda-base-image#18]
I saw [this comment](https://github.com/shelfio/aws-lambda-libreoffice/issues/43#issuecomment-1160830248) about adding new fonts to the base docker image, and I was wondering how I'd go about that? The font I need doesn't seem to be on https://pkgs.org/. 

For reference, I'd like to add [this font](https://fonts.google.com/specimen/Mulish). Any help is appreciated!

**Comment by shiv4623** [comment]
Hi, do you know the full implementation process on how to build image and push image to the ECR?

**Comment by samuelantonioli** [comment]
Hey,
I found a solution. Put your ttf files into a `fonts/` directory in your repository and use the following Dockerfile:

`Dockerfile`
```
FROM public.ecr.aws/shelf/lambda-libreoffice-base:7.4-node16-x86_64
COPY ./ ${LAMBDA_TASK_ROOT}/
COPY ./fonts ${HOME}/.fonts
# dependency not supplied by lambda-libreoffice-base image
# https://github.com/shelfio/aws-lambda-libreoffice/issues/211
RUN fc-cache && yum install java-1.8.0-openjdk-devel -y
RUN npm install
CMD [ "app.handler" ]
```

What it does is it puts the fonts into the $HOME folder and installs them using `fc-cache`.

`package.json`
```
{
  "dependencies": {
    "@shelf/aws-lambda-libreoffice": "^5.0.0"
  }
}
```

`serverless.yml
```
service: pdfgen-lambda
frameworkVersion: '3'
provider:
  name: aws
  ecr:    
    images:
      appimage:
        path: ./
functions:
  libreoffice:
    url: true
    image:
      name: appimage
```

And then

```bash
sls deploy
sls invoke --function libreoffice
```
